/*
 * bahi-khaata — point of sale for Bachat Baazar
 * Copyright (C) 2026 Aakash Sandhyan
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package com.bahikhaata.contracts;

/**
 * Where a barcode came from.
 *
 * <p>A manufacturer code arrives printed on the goods; an internal code is generated by this
 * system, in Code 128 with a reserved prefix, for stock that has no usable barcode of its
 * own. The distinction has to survive in the data: an internal code must always be
 * recognisable as one, so it can never be mistaken for — or collide with — a real
 * manufacturer code.
 *
 * <p>Stored by name in {@code barcode.origin}, which carries a {@code CHECK} constraint over
 * exactly these values; a drift test holds the two in step.
 */
public enum Origin {
    MANUFACTURER,
    INTERNAL
}
