/*
 * bahi-khaata — point of sale for Bachat Bazaar
 * Copyright (C) 2026 Aakash Sandhyan
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package com.bahikhaata.contracts;

/**
 * Where a barcode came from.
 *
 * <p>A manufacturer code arrives printed on the goods; an internal code is generated by this
 * system, in Code 128 with a reserved prefix, for stock that has no usable barcode of its
 * own. The distinction has to survive in the data: an internal code must always be
 * recognisable as one, so it can never be mistaken for — or collide with — a real
 * manufacturer code.
 *
 * <p>Stored by name in {@code barcode.origin}, which carries a {@code CHECK} constraint over
 * exactly these values; a drift test holds the two in step.
 */
public enum Origin {
    /** Printed on the goods by whoever made them — an EAN or UPC a scanner can read. */
    MANUFACTURER,

    /** Generated by this system, in Code 128 with a reserved prefix, for goods with no code. */
    INTERNAL,

    /**
     * A marketplace's own catalogue identifier, such as an Amazon ASIN.
     *
     * <p>Not a barcode. It is not printed on the goods and no scanner will ever read one off a
     * box — what is on the pack is the maker's EAN, or an Amazon FNSKU sticker. It is recorded
     * because it is how a line is matched back to the supplier's manifest, and kept distinct so
     * nobody mistakes it for something scannable.
     */
    MARKETPLACE,

    /**
     * A label identifying one physical unit, applied by a marketplace or warehouse — an Amazon
     * LPN and the like.
     *
     * <p>Scannable, unlike an ASIN, and on returns it is usually the only thing that is: the
     * sticker goes over the manufacturer's barcode. But it names a single item, so the next of
     * the same product carries a different one. Many of these may point at one product, which is
     * why a product was never limited to a single code.
     *
     * <p>Kept apart from {@link #MANUFACTURER} because it cannot be reused. Goods going onto the
     * shelf need a code that will still mean something on the next delivery, which is what
     * {@link #INTERNAL} is for.
     */
    UNIT_LABEL
}
